image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 3.0.0-preview-01-b{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet test -f netcoreapp3.1 -c Release test/ImTools.UnitTests/ImTools.UnitTests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
