image:
  - Visual Studio 2022
  # - Ubuntu # comment until the Ubuntu updated to support .NET 7.0
  - macOS

version: 5.0.0-preview-01-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet test -f net7.0 -c Release test/ImTools.UnitTests/ImTools.UnitTests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
