image:
  - Visual Studio 2022
  - Ubuntu
  - macOS

version: 5.0.0-preview-01-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet test -f net6.0 -c Release -p:DevMode=false test/ImTools.UnitTests/ImTools.UnitTests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
