<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks Condition="'$(DevMode)' == 'true'">net11.0;net10.0;net8.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(DevMode)' != 'true'">net11.0;net10.0;net8.0;net472</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImTools.UnionPlayground\ImTools.UnionPlayground.csproj" />
    </ItemGroup>

</Project>
